---
title: Yoko.is
timezone: America/New_York
email: ysohama@gmail.com
description: This is the personal website and portfolio of Yoko Sakao Ohama, a Brooklyn-based multidisciplinary designer.
baseurl: 
url: http://yoko.is
twitter_username: psyoko
github_username: psyoko
markdown: kramdown
