---
# Every time I make changes to this file I need to restart Jekyll to see it take effect!

title: yoko.cool
timezone: America/New_York
email: ysohama+site@gmail.com
description: This is the personal website and portfolio of Yoko Sakao Ohama, a Brooklyn-based multidisciplinary designer.
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/