---
title: yoko.is
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ysohama@gmail.com
description: This is the personal website and portfolio of Yoko Sakao Ohama, a Brooklyn-based
  multidisciplinary designer.
baseurl: 
url: yoko.is
twitter_username: psyoko
github_username: psyoko
markdown: kramdown
